# Generated by Django 5.1.1 on 2024-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
